eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka
    registry-fetch-interval-seconds: 5
  instance:
    lease-expiration-duration-in-seconds: 6
    lease-renewal-interval-in-seconds: 3

server:
  port: 8091
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /api-ribbon/**
      serviceId: server-ribbon
    api-b:
      path: /api-feign/**
      serviceId: server-feign






